### ISSUE TITLE
Implementation of 'reverse' sorting

### ISSUE THREAD

**Issue by mattrayner** [ukparliament/parliament-ruby#43]
Based on continual use of `.reverse` after calling `sort_by` we should look at implementing a single method that feed off of:
https://github.com/ukparliament/parliament-ruby/blob/master/lib/parliament/response.rb#L38

```ruby
def reverse_sort_by(*parameters)
  sort_by(parameters).reverse!
end
```

This follows the ruby tradition of methods representing the positive and negative i.e. `if` and `unless`, `present?`, and `empty?` etc.

The main thinking behind this is that instead of having `.reverse` called on the application side we will be able to consistently do it on the gem side.

The use of `.reverse!` over `.reverse` is backed up by this stackoverflow article:
http://stackoverflow.com/questions/2642182/sorting-an-array-in-descending-order-in-ruby

We may want to do an additional piece to look at the efficiency of the current `.sort_by` method.

**Comment by katylouise** [comment]
This is now implemented in version 0.5.8 of parliament-ruby.
